### ISSUE TITLE
TypeError: sequence item 1: expected str instance, NoneType found

### ISSUE THREAD

**Issue by jpopelka** [tarmstrong/git2json#16] opened 2018-03-14 17:16 UTC
```
$ git clone https://github.com/fabioparra/TypeScript.git; cd TypeScript
$ git checkout bc691ef78ec
$ ipython3
from git2json.parser import parse_commits
from git2json import run_git_log
list(parse_commits(run_git_log('.git')))

TypeError                                 Traceback (most recent call last)
<ipython-input-4-a4fe5c202781> in <module>()
----> 1 list(parse_commits(run_git_log('.git')))

~/.virtualenvs/bayesian/lib/python3.6/site-packages/git2json/parser.py in parse_commits(data)
     47         full_commit = rc.groups()[0]
     48         parts = RE_COMMIT.match(full_commit).groupdict()
---> 49         parsed_commit = parse_commit(parts)
     50         yield parsed_commit
     51 

~/.virtualenvs/bayesian/lib/python3.6/site-packages/git2json/parser.py in parse_commit(parts)
     71         parse_message_line(msgline)
     72         for msgline in
---> 73         parts['message'].splitlines()
     74     )
     75     commit['changes'] = [

TypeError: sequence item 1: expected str instance, NoneType found

```

**Comment by tarmstrong** [comment] 2018-03-25 02:05
I believe this has been fixed with https://github.com/tarmstrong/git2json/pull/17 but since I wasn't able to reproduce this problem locally, it would be helpful to have your confirmation that it is fixed.

**Closed** 2018-03-25 02:05 UTC
